version: '3.7'
services:
  headers-dev:
    build:
      context: .
      target: node
      args:
        NODE_VERSION: ${NODE_VERSION-13.7.0}
    ports:
      - "3004:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    # Copy over the .ssh folder and make sure the correct user owns it
    entrypoint: >
      sh -c 'npm install && 
      docker-entrypoint.sh $${0} "$$@"' 
    command:  ["npm", "run", "offline", "--", "--watch"]
volumes:
  node_modules: