sudo: required
language: minimal
branches:
  only:
    - master
services:
  - docker
script:
  - bash scripts/travis.sh
# From https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
cache:
  bundler: true
  directories:
    - $HOME/docker
before_install:
  # Load cached docker images
  - ls $HOME/docker
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' |
    xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 $(docker history -q $0) | gzip -2 > $HOME/docker/$1.tar.gz'
