os: linux
dist: bionic
language: shell
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
      script: make unit
    - stage: Test
      script: make integration
    - stage: Test
      before_install: export STAGE=e2e-$(date +%s%N)
      install: make STAGE_E2E=$STAGE e2e-deploy
      script:
        - make e2e
        - make e2e-lighthouse
        - make e2e-observatory
      after_success: make STAGE_E2E=$STAGE e2e-destroy
      after_failure: make STAGE_E2E=$STAGE e2e-destroy

    - stage: Deploy
      script: 
        - make infra-prod
        - make deploy-prod
