os: linux
dist: bionic
language: shell
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: Test
      script: make unit
    - stage: Test
      script: make integration
    - stage: Test
      before_install: export STAGE=e2e-$TRAVIS_BRANCH
      # Run the builds while deploying as they take a while
      install: make -j4 STAGE_E2E=$STAGE e2e-deploy build e2e-build
      script:
        - make -j3 e2e e2e-lighthouse e2e-observatory
      after_success: make STAGE_E2E=$STAGE e2e-destroy
      after_failure: make STAGE_E2E=$STAGE e2e-destroy

    - stage: Deploy
      script: 
        # Again, run builds while deploying infra as they take a while
        - make -j2 infra-prod build
        - make -j2 deploy-prod
