sudo: required
language: minimal
branches:
  only:
    - master
dist: bionic
services:
  - docker
jobs:
  include:
    - stage: Test
      script: make unit
    - stage: Test
      script: make integration
    - stage: Test
      before_install: export STAGE=e2e-$(date +%s%N)
      install: make STAGE_E2E=$STAGE e2e-deploy
      script:
        - make e2e
        - make e2e-lighthouse
      after_script: make STAGE_E2E=$STAGE e2e-destroy

    - stage: Deploy
      deploy: 
        - make infra-prod
        - make deploy-prod
