version: '3.7'
services:
  # Makes sure the builder has run and copies over the build files to a shared volume so that terraform can use them later
  build:
    build:
      context: .
      target: builder
      args:
        NODE_VERSION: ${NODE_VERSION} #Comes from .env file
    volumes:
      - out:/app/out-shared
    command: |
      sh -c " \
        rm -rf out-shared/* && \
        cp -rf out/* out-shared/"
  # This service MUST be run after the build service has completed 
  deploy:
    build: 
      context: .
      dockerfile: deploy.Dockerfile 
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION} #Comes from .env file
    entrypoint: 'sh -c ''terraform init -input=false && terraform $${0} "$$@" -var "build=out" -var "stage=prod"'''
    # Init and apply, specifying the directory to take the files from as /app/out
    command: "apply -input=false -auto-approve"
    working_dir: /app
    volumes:
      - .:/app
      - out:/app/out
    secrets:
      - source: aws
        target: /root/.aws
volumes:
  out:
secrets:
  aws:
    file: ~/.aws


    