version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION} #Comes from .env file
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next:/app/.next
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: ssh
        target: /root/.ssh_host
    environment:
      - NODE_ENV=development
      - REACT_APP_COGNITO_HOST=http://localhost:3002
      - REACT_APP_CLIENT_ID=test
      - REACT_APP_REDIRECT_URL=http://localhost:3000/auth-demo
      - REACT_APP_USER_API_URL=http://localhost:8000
    # Copy over the .ssh folder and make sure the correct user owns it
    entrypoint: >
      sh -c 'cp -rfd /root/.ssh_host /root/.ssh && 
      chmod -R 400 /root/.ssh && 
      yarn install &&
      docker-entrypoint.sh $${0} "$$@"'
    command:  ["yarn", "run", "dev"]
  # Would have used localstack to run cognito but you have to pay for it :(
  auth-demo-iam:
    image: node:${NODE_VERSION}-alpine
    ports:
      - "3002:3002"
    working_dir: /app
    volumes:
      - ./services/auth-demo/iam/test-oidc-provider:/app
      - auth_demo_iam_node_modules:/app/node_modules
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c 'cp -rfd /root/.ssh_host /root/.ssh &&
      chmod -R 400 /root/.ssh && 
      npm install &&
      $${0} "$$@"'
    command: "npm start"
    secrets:
      - source: ssh
        target: /root/.ssh_host
volumes:
  node_modules:
  next:
  auth_demo_iam_node_modules:
secrets:
  ssh:
    file: ~/.ssh