version: '3.7'
services:
  dev:
    build:
      context: .
      target: node
    ports:
      - "9929:9929"
      - "9230:9230"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next:/app/.next
      - ~/.gitconfig:/root/.gitconfig
    secrets:
      - source: ssh
        target: /root/.ssh_host
    environment:
      - NODE_ENV=development
    # Copy over the .ssh folder and make sure the correct user owns it
    entrypoint: 'sh -c ''cp -rfd /root/.ssh_host /root/.ssh && chmod -R 400 /root/.ssh && docker-entrypoint.sh $${0} "$$@"''' 
    command:  ["yarn", "run", "dev"]
volumes:
  node_modules:
  next:
secrets:
  ssh:
    file: ~/.ssh