version: '3.7'
services:
  e2e:
    build:
      context: e2e/lighthouse
    command: [ "./cmd.sh" ]
    environment: 
      - URLS=${BASE_URL},${BASE_URL}/auth-demo
      - MIN_PERFORMANCE_SCORE=85
      - MIN_ACCESIBILITY_SCORE=95
      - MIN_BEST_PRACTICES_SCORE=100
      - MIN_SEO_SCORE=90
      - MIN_PWA_SCORE=100