version: '3.7'
services:
  e2e:
    build:
      context: e2e/
    entrypoint: "cypress run"
    environment: 
      - CYPRESS_baseUrl=${CYPRESS_baseUrl}
    command: ["--browser", "chrome", "-e", "TAGS=not @ignore"]