version: '3.7'
services:
  e2e:
    build:
      context: e2e/
    entrypoint: >
      /bin/sh -c '
        wait-on http://router && 
        wait-on tcp:auth-demo-iam:3002 &&
        wait-on tcp:auth-demo-api:3003 &&
        wait-on tcp:auth-demo-dynamodb:8000 &&
        cypress run $${0} "$$@"'
    environment: 
      - CYPRESS_baseUrl=http://router
    command: ["--browser", "chrome"]
  # Cypress doesn't like moving between multiple domains, so adding in routing here so that the domain doesn't change
  # Currently not sustainable as urls are now all relative to router and so can't overlap across services
  # Also, smaller point, but doesn't check cross-origin is setup correctly for API calls
  router:
    image: nginx:${NGINX_VERSION}-alpine
    entrypoint: >
      /bin/sh -c '
        rm -rf /usr/share/nginx/html/* && 
        echo "server { 
          listen       80; 
          server_name  leonyork-com; 
          location /oauth2 { 
            proxy_pass  http://auth-demo-iam:3002;
            proxy_set_header Host router;
          } 
          location /logout { 
            proxy_pass  http://auth-demo-iam:3002;
            proxy_set_header Host router;
          } 
          location /interaction {
            proxy_pass  http://auth-demo-iam:3002;
            proxy_set_header Host router;
          }
          location /user {
            proxy_pass  http://auth-demo-api:3003;
            proxy_set_header Host router;
          }
          location / { 
            proxy_pass  http://web;
          } 
        }" > /etc/nginx/conf.d/default.conf &&
      $${0} "$$@"'
    command: ["nginx", "-g", "daemon off;"]
    ports: 
      - "80:80"
    depends_on: 
      - web
      - auth-demo-iam
  web:
    build: 
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION} #Comes from .env file
        NGINX_VERSION: ${NGINX_VERSION} #Comes from .env file
        COGNITO_HOST: http://router
        CLIENT_ID: test
        REDIRECT_URL: http://router/auth-demo
        USER_API_URL: http://router
  auth-demo-iam:
    image: node:${NODE_VERSION}-alpine
    working_dir: /app
    volumes:
      - ./services/auth-demo/iam/test-oidc-provider:/app
      - auth_demo_iam_node_modules:/app/node_modules
    entrypoint: >
      sh -c 'npm install &&
      $${0} "$$@"'
    command: "npm start"
    environment: 
      - REDIRECT_URL=http://router/auth-demo
  auth-demo-api:
    build:
      context: ./services/auth-demo/api
      args:
        NODE_VERSION: ${NODE_VERSION}
        USERS_TABLE: users
    environment:
      - USER_STORE_API_SECURED_ISSUER=http://auth-demo-iam:3002
      - USER_STORE_API_ACCESS_CONTROL_ALLOW_ORIGIN=http://router
      - DYNAMODB_HOST=auth-demo-dynamodb
      - USERS_TABLE=users
  auth-demo-dynamodb:
    build:
      context: ./services/auth-demo/api
      dockerfile: dynamo.Dockerfile
      args:
        TABLE_NAME: users
volumes:
  auth_demo_iam_node_modules: