version: '3.7'
services:
  client-app-build:
    build:
      context: .
      dockerfile: build.Dockerfile
    working_dir: /app
    volumes: 
      - ./out:/app/out
    environment: 
      - REACT_APP_COGNITO_HOST=${REACT_APP_COGNITO_HOST}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_URL=${REACT_APP_URL}
      - REACT_APP_USER_API_URL=${REACT_APP_USER_API_URL}
      - NODE_ENV=production