version: '3.7'
services:
  client-app-deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    working_dir: /app
    volumes: 
      - ./out:/app/out
    environment: 
      - AWS_SECRET_KEY_ID=${AWS_ACCESS_KEY_ID?You must set the environment variable AWS_ACCESS_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY?You must set the environment variable AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_ID=${S3_BUCKET_ID}
      - AWS_REGION=${REGION}