service: cognito-dev-sign-up

provider:
  name: aws
  runtime: nodejs10.x

functions:
  cognito-sign-up:
    handler: src/handlers/sign-up.handler
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: PreSignUp
          existing: true
        
plugins:
  - serverless-webpack

#Package individually so that each function is smaller (i.e. tiny bit quicker startup!!!)
package:
    individually: true

custom:
    webpack:
        includeModules:
        forceExclude:
            - aws-sdk