name: Commit Lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  commit-lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 
      - name: Check the commits for the pull request have been formatted correctly
        run: make COMMIT_LINT_VARS='--from "${{ github.event.pull_request.base.sha }}" --to "${{ github.event.pull_request.head.sha }}"' commit-lint